/* Generated by tools/snnc/snnc.py from model/training/runs/snn_h128_k2_T20. Do not edit. */
#ifndef NETCFG_H
#define NETCFG_H

#define NET_T        20
#define NET_K        2
#define NET_VTH1     248
#define NET_VTH2     295
#define NET_HIDDEN   128

#endif
