"""Emit the images from images.hex as a C array for the bare-metal encoder.

All images in the vector set are emitted, so one build can switch between them
at runtime (the board reads MMIO_SW). IMAGE_INDEX is the default for apps that
pick an image at compile time instead.

    python3 scripts/gen_image_h.py [default_index] [out_path]
"""
import sys
from pathlib import Path

VEC = Path("verif/vectors/snn_h128_k2_T20/images.hex")
PIXELS = 784


def read_hex(path):
    vals = []
    for line in path.read_text().splitlines():
        line = line.split("//")[0]
        vals.extend(int(tok, 16) for tok in line.split())
    return vals


def main():
    idx = int(sys.argv[1]) if len(sys.argv) > 1 else 0
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("sw/libsnn/image.h")

    vals = read_hex(VEC)
    if len(vals) % PIXELS:
        sys.exit(f"{VEC}: {len(vals)} values is not a multiple of {PIXELS}")
    n_images = len(vals) // PIXELS
    if not 0 <= idx < n_images:
        sys.exit(f"image index {idx} out of range (file holds {n_images})")

    lines = [f"/* Generated by scripts/gen_image_h.py from {VEC}. Do not edit. */",
             "#ifndef IMAGE_H",
             "#define IMAGE_H",
             "",
             f"#define IMAGE_COUNT  {n_images}",
             f"#define IMAGE_INDEX  {idx}",
             f"#define IMAGE_PIXELS {PIXELS}",
             "",
             "static const unsigned char images[IMAGE_COUNT][IMAGE_PIXELS] = {"]
    for n in range(n_images):
        px = vals[n * PIXELS:(n + 1) * PIXELS]
        lines.append(f"  {{ /* image {n} */")
        for i in range(0, PIXELS, 12):
            lines.append("    " + ", ".join(f"0x{v:02x}" for v in px[i:i + 12]) + ",")
        lines.append("  },")
    lines += ["};", "", "#endif", ""]

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"{out}: {n_images} images, {PIXELS} pixels each, "
          f"{n_images * PIXELS} bytes of rodata, default index {idx}")


if __name__ == "__main__":
    main()
