
import argparse
import json
import sys
from pathlib import Path

# Hardware limits. 
LANES = 4          # neurons swept per cycle, rtl/accel/accel_defs.vh
H_MAX = 128        # spk1 depth and acc_mem DEPTH
INPUT_MAX = 784    # ev_mem bank depth
OUT_MAX = LANES * 3    # layer 2 sweeps word_cnt 0..2
T_MAX = 31         # T register is 5 bits
K_MIN, K_MAX = 1, 5    # K register is 3 bits
VTH_MIN, VTH_MAX = -32768, 32767   # thresholds are compared against int16 v


def check(cfg):
    
    bad = []
    h, i, o = cfg["hidden_size"], cfg["input_size"], cfg["output_size"]

    if i > INPUT_MAX:
        bad.append(f"input_size {i} exceeds the {INPUT_MAX}-entry event bank")
    if h > H_MAX:
        bad.append(f"hidden_size {h} exceeds H_MAX {H_MAX} (spk1/acc_mem depth)")
    if h < LANES or h % LANES:
        bad.append(f"hidden_size {h} must be a multiple of LANES {LANES}")
    elif (h // LANES) & (h // LANES - 1):
        bad.append(f"hidden_size {h} must be {LANES} * a power of two")
    if o > OUT_MAX:
        bad.append(f"output_size {o} exceeds {OUT_MAX}, the most neurons layer 2 "
                   f"can sweep (3 words x {LANES} lanes)")
    if not 1 <= cfg["T"] <= T_MAX:
        bad.append(f"T {cfg['T']} outside 1..{T_MAX} (5-bit register)")
    if not K_MIN <= cfg["k"] <= K_MAX:
        bad.append(f"k {cfg['k']} outside {K_MIN}..{K_MAX} (3-bit register)")
    for layer, v in cfg["v_th_int"].items():
        if not VTH_MIN <= v <= VTH_MAX:
            bad.append(f"v_th_int[{layer}] {v} does not fit int16")
    return bad


def emit(cfg, run, out):
    lines = [
        f"/* Generated by tools/snnc/snnc.py from {run}. Do not edit. */",
        "#ifndef NETCFG_H",
        "#define NETCFG_H",
        "",
        f"#define NET_T        {cfg['T']}",
        f"#define NET_K        {cfg['k']}",
        f"#define NET_VTH1     {cfg['v_th_int']['fc1']}",
        f"#define NET_VTH2     {cfg['v_th_int']['fc2']}",
        f"#define NET_HIDDEN   {cfg['hidden_size']}",
        "",
        "#endif",
        "",
    ]
    out.write_text("\n".join(lines))


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("run", help="training run directory holding config.json")
    p.add_argument("-o", "--out", default="sw/libsnn/netcfg.h")
    args = p.parse_args()

    run = Path(args.run)
    cfg_path = run / "config.json"
    if not cfg_path.exists():
        sys.exit(f"no config.json in {run}")
    cfg = json.loads(cfg_path.read_text())

    bad = check(cfg)
    if bad:
        print(f"{run} is outside the supported network class:", file=sys.stderr)
        for reason in bad:
            print(f"  - {reason}", file=sys.stderr)
        sys.exit(1)

    out = Path(args.out)
    emit(cfg, run, out)
    print(f"{out}: {cfg['input_size']}-{cfg['hidden_size']}-{cfg['output_size']} "
          f"T={cfg['T']} k={cfg['k']} "
          f"vth={cfg['v_th_int']['fc1']}/{cfg['v_th_int']['fc2']}")


if __name__ == "__main__":
    main()
